run:
  deadline: 30m
  tests: true

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  misspell:
    locale: US
#  wrapcheck:
#    ignoreSigs:
#      - status.Error
#      - .Errorf(
#      - errors.New(
#      - errors.Unwrap(
#      - .Wrap(
#      - .Wrapf(
#      - .WithMessage(

linters:
  enable:
    - errorlint
    - goerr113
    - nilerr
#    - wrapcheck (https://github.com/tomarrell/wrapcheck/issues/2)
    - goimports
    - gofmt
    - bodyclose
    - goconst
    - prealloc
    - rowserrcheck
    - misspell
    - gosec
    - unconvert
    - errcheck

issues:
  exclude-rules:
    - path: app/domain/vos/account.go
      source: "conciliateCredit"
      linters:
        - gosec

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

skip-dirs:
  - gen/*
  - docs/*
skip-files:
  - ".*\\.pb\\.go$"